version: '3'
services:
  dev:
    build: .
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "nodemon -L --watch src --exec 'ts-node src/server.ts'"
    ports:
      - 9090:8080

